repos:
- repo: local
  hooks:
    - id: ruff check --fix
      name: ruff check --fix
      entry: uv run ruff check --fix
      language: system
      types_or: [python, jupyter]
    - id: ruff format
      name: ruff format
      entry: uv run ruff format
      language: system
      types_or: [python, jupyter]
