on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable caching and define a custom cache key suffix
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: sync dependencies
        run: uv sync
      - name: build output
        run: make publish
      - name: upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

  deploy:
    needs: build
    if: github.ref_name == 'dev'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

