name: Deploy to GitHub Pages
on:
  push:
    branches: ["dev"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requiremets: "-r requirements.txt"
      theme: "https://github.com/johnpaton/flex-mod.git"
      python: "3.9"
      siteurl: "https://johnpaton.net"
      feed_domain: "https://johnpaton.net"
      